name: Update datasets

on:
  workflow_dispatch:
  schedule:
    # Each hour https://crontab.guru
    - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build reports
        run: python run.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: "github_actions"
          message: "🤖 Update datasets"
